### PR TITLE
Emit dispatch message when whole message (payload) has invalid encoding

### LINKED ISSUE #612: Event for payload decoding error
Message delivery on the target chain should generate an event in case it fails to decode the payload. Currently events are not consistent, cause we do report an error in case of `spec_version` inconsistency but not if the payload fails to be decoded. We should have an event for every message in any case.

### PR DESCRIPTION
**Pull request by svyatonik**
closes #612

### CODE REVIEW

**Review by tomusdrw — DISMISSED** [review]
See: https://github.com/paritytech/parity-bridges-common/pull/663#discussion_r560933590

File: bin/runtime-common/src/messages.rs [hunk 1]
```diff
@@ -385,12 +387,18 @@ pub mod target {
 		}
 
 		fn dispatch(message: DispatchMessage<Self::DispatchPayload, BalanceOf<BridgedChain<B>>>) {
+			let message_id = (message.key.lane_id, message.key.nonce);
 			if let Ok(payload) = message.data.payload {
 				pallet_bridge_call_dispatch::Module::<ThisRuntime, ThisCallDispatchInstance>::dispatch(
```
Comment (tomusdrw) [inline bin/runtime-common/src/messages.rs:392]: I know understand why we need to decode the message before this point (getting weight info), but I still don't like the explicit `note_rejected_message` call, could we just pass the entire `message.data.payload` (instead of `payload.0`) to the `dispatch` function?

I.e. I'm proposing to change the `fn dispatch` function from the trait to take `Result<...>` instead of just the payload - this emitting the event can stay internal to `call-dispatch`.

**Review by tomusdrw — APPROVED** [review]

File: modules/call-dispatch/src/lib.rs [hunk 2]
```diff
@@ -183,7 +185,17 @@ impl<T: Config<I>, I: Instance> MessageDispatch<T::MessageId> for Module<T, I> {
 		message.weight
 	}
 
-	fn dispatch(bridge: InstanceId, id: T::MessageId, message: Self::Message) {
+	fn dispatch(bridge: InstanceId, id: T::MessageId, message: Result<Self::Message, ()>) {
```
Comment (HCastano) [inline modules/call-dispatch/src/lib.rs:188]: Since we're not actually using the `Err` type of the `Result` we might as well just make this an `Option<Self::Message>`

**Review by HCastano — APPROVED** [review]
