### PR TITLE
local.Dockerfile for building images from locally built binaries

### LINKED ISSUE #2141: Build docker images by copying prebuilt binary
Our docker builds are super slow (git clone, cargo deps, release build from the scratch). Let's add dockerfile that will just copy prebuilt image from the target directory. This:
- will make builds super fast, because most probably you've already cloned and built all deps;
- will make it easier to build custom images e.g. with overrriden dependencies, sometimes required to debug something.

Like this (still experimenting):
```Dockerfile
# Builds images used by the bridge.
#
# In particular, it can be used to build Substrate nodes and bridge relayers. The binary that gets
# built can be specified with the `PROJECT` build-arg. For example, to build the `substrate-relay`
# you would do the following:
#
# `docker build . -t local/substrate-relay --build-arg=PROJECT=substrate-relay`
#
# See the `deployments/README.md` for all the available `PROJECT` values.

FROM docker.io/library/ubuntu:20.04 as runtime

USER root
WORKDIR /home/root

# show backtraces
ENV RUST_BACKTRACE 1
ENV DEBIAN_FRONTEND=noninteractive

RUN set -eux; \
	apt-get update && \
	apt-get install -y --no-install-recommends \
        curl ca-certificates libssl-dev && \
    update-ca-certificates && \
	groupadd -g 1000 user && \
	useradd -u 1000 -g user -s /bin/sh -m user && \
	# apt clean up
	apt-get autoremove -y && \
	apt-get clean && \
	rm -rf /var/lib/apt/lists/*

# switch to non-root user
USER user

WORKDIR /home/user

ARG PROFILE=release
ARG PROJECT=substrate-relay

COPY --chown=user:user ./target/${PROFILE}/${PROJECT} ./

# check if executable works in this container
RUN ./${PROJECT} --version

ENV PROJECT=$PROJECT
ENTRYPOINT ["/bin/sh"]
```

And:
```
docker build . --build-arg=PROJECT=rialto-parachain-collator -f local.Dockerfile -t local/rialto-parachain-collator
```

.dockerignore (just an example):
```
*
!target/release/millau-bridge-node
!target/release/rialto-bridge-node
!target/release/rialto-parachain-collator
!target/release/substrate-relay
```

### PR DESCRIPTION
**Pull request by svyatonik**
closes #2141

### CODE REVIEW

File: local.Dockerfile [hunk 1]
```diff
@@ -0,0 +1,47 @@
...
+#
+# In particular, it can be used to build Substrate nodes and bridge relayers. The binary that gets
+# built can be specified with the `PROJECT` build-arg. For example, to build the `substrate-relay`
+# you would do the following:
+#
+# `docker build ./target -f local.Dockerfile -t local/substrate-relay --build-arg=PROJECT=substrate-relay`
+#
+# See the `deployments/README.md` for all the available `PROJECT` values.
+
+FROM docker.io/library/ubuntu:20.04 as runtime
```
Comment (serban300) [inline local.Dockerfile:13]: Nit: This needs to be the same as the local OS. Maybe it would be worth having a comment about this.

**Review by bkontur — APPROVED** [review]

File: local.Dockerfile [hunk 2]
```diff
@@ -0,0 +1,47 @@
...
+# show backtraces
+ENV RUST_BACKTRACE 1
+ENV DEBIAN_FRONTEND=noninteractive
+
+RUN set -eux; \
+	apt-get update && \
+	apt-get install -y --no-install-recommends \
+        curl ca-certificates libssl-dev && \
+    update-ca-certificates && \
+	groupadd -g 1000 user && \
```
Comment (serban300) [inline local.Dockerfile:27]: I'm using ubuntu 23.04 and gid 1000 doesn't work for me. Could we use another value here ? 1001 or 2000 for example ?

File: scripts/build-containers.sh [hunk 3]
```diff
@@ -1,7 +1,22 @@
...
+        time cargo build -p millau-bridge-node --release
+        time cargo build -p rialto-parachain-collator --release
+    fi
+
+    # following (using DOCKER_BUILDKIT) requires docker 19.03 or above
+    DOCKER_BUILDKIT=1 time docker build . -f local.Dockerfile -t local/substrate-relay --build-arg=PROJECT=substrate-relay
+    DOCKER_BUILDKIT=1 time docker build . -f local.Dockerfile -t local/rialto-bridge-node --build-arg=PROJECT=rialto-bridge-node
+    DOCKER_BUILDKIT=1 time docker build . -f local.Dockerfile -t local/millau-bridge-node --build-arg=PROJECT=millau-bridge-node
+    DOCKER_BUILDKIT=1 time docker build . -f local.Dockerfile -t local/rialto-parachain-collator --build-arg=PROJECT=rialto-parachain-collator
+fi
```
Comment (serban300) [inline scripts/build-containers.sh:22]: Nit: Could we also clean the old images at the end ?

**Review by serban300 — APPROVED** [review]

File: local.Dockerfile (hunk 1 above)
Comment (svyatonik) [reply local.Dockerfile:14]: Moved compatibility comment here. Out of curiosity - `substrate-relay` that is built on 23.04 doesn't work on 20.04?

File: local.Dockerfile (hunk 2 above)
Comment (svyatonik) [reply local.Dockerfile]: Changed to 1001

File: scripts/build-containers.sh (hunk 3 above)
Comment (svyatonik) [reply scripts/build-containers.sh:22]: I'm not sure what old images do you mean?

File: local.Dockerfile (hunk 1 above)
Comment (serban300) [reply local.Dockerfile:14]: Doesn't seem to work. At least I'm getting the following error:

```
./substrate-relay: error while loading shared libraries: libssl.so.3: cannot open shared object file: No such file or directory
The command '/bin/sh -c ./${PROJECT} --version' returned a non-zero code: 127
```

File: scripts/build-containers.sh (hunk 3 above)
Comment (serban300) [reply scripts/build-containers.sh:22]: For example when we generate a new `local/rialto-bridge-node:latest`, AFAIK the previous `local/rialto-bridge-node:latest` will not be removed automatically. Or at least there will be layers of its storage that are not needed anymore, but they are kept. It would be nice to remove them. Not sure if possible. I usually run `docker rmi -f $(docker images -f dangling=true -q)`, but this deletes all dangling images.

Comment (svyatonik) [reply scripts/build-containers.sh:22]: OK, thanks for explanation. But imo let's not do this in script - removal looks like a manual action to me. And `docker system prune` (or something like that) isn't super complex to call sometimes.

Comment (serban300) [reply scripts/build-containers.sh:22]: Ok, sure
