### PR TITLE
Fix send_message_worst_case benchmark

### LINKED ISSUE #569: Fix send_message_worst_case benchmark
It is broken after #558

### PR DESCRIPTION
**Pull request by svyatonik**
closes #569

### CODE REVIEW

File: bin/rialto/runtime/src/lib.rs [hunk 1]
```diff
@@ -843,7 +843,9 @@ impl_runtime_apis! {
 							* sp_std::cmp::min(factor, WORST_MESSAGE_SIZE_FACTOR),
 					};
 					let message_payload = vec![0; message_size as usize];
-					let dispatch_origin = pallet_bridge_call_dispatch::CallOrigin::SourceAccount(Default::default());
```
Comment (HCastano) [inline bin/rialto/runtime/src/lib.rs:846]: Was it broken because of this?

**Review by HCastano — APPROVED** [review]
Looks fine, but I don't quite understand what how benchmarks were broken by #558.

If it failed to compile then we should add the `message-lane` benchmarks to the CI soon.

File: bin/rialto/runtime/src/lib.rs (hunk 1 above)
Comment (svyatonik) [reply bin/rialto/runtime/src/lib.rs:846]: Yes
